---
# tasks file for ceph-deploy-common


- include: ceph-upstream-repo.yml
  when: ceph_repo == 'ceph'

- debug:
    msg: "Ceph from distro repo is not supported yet"
  when: ceph_repo == 'distro'

- name: install ceph-deploy
  apt:
    name: ceph-deploy
    state: present
    update_cache: yes

- name: create {{ ceph_cluster_dir }}
  file:
    path: "{{ ceph_cluster_dir }}"
    state: directory
  when: inventory_hostname == groups['ceph-mon'][0]

#TODO: add ntp setup
#- include: ntp.yml

- block:
    - name: add rbd devices to be classified as network storage
      lineinfile:
        path: /etc/init/networking.conf
        line: '\1/dev/rbd*|\2'
        regexp: '(^\W+)(/dev/nbd\*\|/dev/nd\[a-z\]\*\|/dev/etherd/e\*\))'
        backrefs: yes
        backup: yes
      with_items:
        - 0
        - 1

    - name: disable ifaces shutdown on os shutdown
      lineinfile:
        path: /etc/init/networking.conf
        line: '#\1'
        regexp: '(^\W+ifdown -a --exclude=lo)'
        backrefs: yes
        backup: yes

  when: "{{ colocate_k8s }}"
