---
# tasks file for ceph-swift

- name: install swift client
  apt:
    name: python-swiftclient
    state: present

- block:
#   - name:
#     set_fact:
#       radosgw_admin_head: "
    - include: radosgw-users.yml
      with_items: "{{ swift_store }}"
      loop_control:
        loop_var: swift_conf
#    - name:
#      debug: var=item.user
#      with_items: "{{ swift_store }}"
  when: inventory_hostname == groups['ceph-rgw'][0]
